## Importing the required data

- upload jobs residency xlsx table to 'data'

In [1]:
!mkdir data

## Converting xlsx file to pandas dataframe

- install openpyxl, import load_workbook and pandas
- load xlsx workbook --> access required sheet
- convert to dataframe with .values

In [1]:
#to open xlsx files
!pip install openpyxl

Requirement already satisfied: openpyxl in /home/nbuser/anaconda3_501/lib/python3.6/site-packages (2.5.8)
Requirement already satisfied: jdcal in /home/nbuser/anaconda3_501/lib/python3.6/site-packages (from openpyxl) (1.4)
Requirement already satisfied: et-xmlfile in /home/nbuser/anaconda3_501/lib/python3.6/site-packages (from openpyxl) (1.0.1)

In [2]:
import pandas as pd

In [3]:
import numpy as np

In [4]:
from openpyxl import load_workbook
wb2 = load_workbook('./data/place-residence-place-work-local-authorities-uk-2011.xlsx', data_only=True)

In [5]:
ws2 = wb2["London boroughs plus regions"]
jobres = pd.DataFrame(ws2.values)

## Clearing dataframe

- drop last rows by slicing
- aggregate all value outside London into one 'Outside London' category with Code 'X00000000'
- make coloumn 0 and row 0 axes labels

In [6]:
jobres = jobres[:47] #cutting of all empty rows

In [7]:
#aggregating all rows with data outside london
reg1 = jobres[35:46] 

tot_row = pd.DataFrame(reg1.sum()).T
tot_row[1] = 'Outside London'
tot_row[0].loc[0] = "X00000000"

jobres = pd.concat([jobres, tot_row], ignore_index=True)
jobres.drop(reg1.index, axis=0, inplace=True)
jobres.drop(2, axis=1, inplace=True)

jobres.tail()

,0,1,3,4,5,6,7,8,9,10,...,41,42,43,44,45,46,47,48,49,50
32,E41000322,Waltham Forest,976,1001,100,723,144,6137,183,564,...,1056,126,4,56,53,9270,154,18384,100,121461
33,E41000323,Wandsworth,36,431,81,738,348,8626,1480,1241,...,6714,334,7,72,46,16863,328,13949,266,179439
34,E41000324,"Westminster,City of London",33,712,36,1506,108,7593,164,1080,...,2436,264,8,52,25,16762,516,7972,537,117303
46,None,Total workers in workplace,43647,89244,54602,81732,81922,250615,88324,97801,...,3210752,2008917,598518,1995044,1086986,3138022,63473,2513680,52954,30008634
47,X00000000,Outside London,10042,17220,15370,11363,13867,51664,13837,14621,...,3058833,2001820,598316,1993027,1085680,2750521,56467,2092486,46699,25986853

In [8]:
#storing the borough/code key for later usage
key = jobres[[0, 1]].iloc[3:35]
key[1].loc[34] = "Westminster" 
PROC_DATA_PATH = '~/library/data/processed/'
key.to_csv(PROC_DATA_PATH + 'E41key.csv')

In [9]:
jobres_t = jobres.T

In [10]:
#aggregating all former columns with data outside london
reg1 = jobres_t[35:45]
offs = jobres_t[46:47]
outuk = jobres_t[48:49]
reg1 = pd.concat([reg1, offs], join = 'inner', ignore_index=True)
reg1 = pd.concat([reg1, outuk], join='inner', ignore_index=True)

tot_row = pd.DataFrame(reg1.sum()).T
tot_row[1] = 'Outside London'
tot_row[0].loc[0] = "X00000000"

jobres_t = pd.concat([jobres_t, tot_row], ignore_index=True)

jobres_t.tail()

,0,1,2,3,4,5,6,7,8,9,...,27,28,29,30,31,32,33,34,46,47
46,OD0000002,None,Offshore installation,95,310,90,306,180,272,232,...,185,178,269,92,271,154,328,516,63473,56467
47,OD0000003,None,No fixed place,10296,19791,11979,21202,14197,8722,17006,...,14113,7634,14351,10050,10282,18384,13949,7972,2513680,2092486
48,OD0000004,None,Outside UK,57,343,115,197,195,265,192,...,163,272,187,124,154,100,266,537,52954,46699
49,None,Total residents in work,Total,75493,172470,110680,148292,152363,110168,173926,...,125362,99916,147995,98207,121244,121461,179439,117303,30008634,25986853
50,X00000000,Outside London,North WestYorkshire and The HumberEast Midland...,6167,13371,12752,7804,11395,4300,17238,...,9661,10389,5545,13794,4903,6929,9253,5389,19673047,19387162

In [11]:
#simplifying dataframe
jobres_t[1].loc[47] = "No fixed place"
jobres_t[1].loc[45] = "Mainly work at or from home"

In [12]:
jobres_t.drop(34, axis=0, inplace=True)
jobres_t.drop(35, axis=0, inplace=True)
jobres_t.drop(36, axis=0, inplace=True)
jobres_t.drop(37, axis=0, inplace=True)
jobres_t.drop(38, axis=0, inplace=True)
jobres_t.drop(39, axis=0, inplace=True)
jobres_t.drop(40, axis=0, inplace=True)
jobres_t.drop(41, axis=0, inplace=True)
jobres_t.drop(42, axis=0, inplace=True)
jobres_t.drop(43, axis=0, inplace=True)
jobres_t.drop(44, axis=0, inplace=True)
jobres_t.drop(46, axis=0, inplace=True)
jobres_t.drop(48, axis=0, inplace=True)

jobres_t.drop(2, axis=1, inplace=True)

In [13]:
jobres_t[46].loc[0] = "TOTAL_WORKERS"
jobres_t[0].loc[49] = "TOTAL_RESIDENTS"
jobres_t[0].loc[0] = "Code"

In [14]:
jobres_t.drop(1, axis=1, inplace=True)
jobres_t.drop(1, axis=0, inplace=True)

In [15]:
jobres = jobres_t.T
jobres

,0,2,3,4,5,6,7,8,9,10,...,28,29,30,31,32,33,45,47,49,50
0,Code,E41000293,E41000294,E41000295,E41000296,E41000297,E41000298,E41000299,E41000300,E41000301,...,E41000319,E41000320,E41000321,E41000322,E41000323,E41000324,OD0000001,OD0000003,TOTAL_RESIDENTS,X00000000
3,E41000293,14650,280,155,290,104,1855,110,250,653,...,1218,89,4279,1292,235,6350,4764,10296,75493,6167
4,E41000294,144,36031,42,5908,91,14006,131,1787,4457,...,2357,68,3461,585,567,24662,21611,19791,172470,13371
5,E41000295,323,131,25876,161,4846,2391,510,177,175,...,4177,136,3656,241,599,12986,8663,11979,110680,12752
6,E41000296,56,6268,37,27338,84,8735,189,8195,678,...,2061,101,2405,276,846,22519,13058,21202,148292,7804
7,E41000297,135,209,2962,199,41000,4145,4879,275,157,...,6175,887,4946,219,1297,22449,16167,14197,152363,11395
8,E41000298,51,1918,47,1677,65,23151,98,718,415,...,2507,49,4192,254,594,29719,14893,8722,110168,4300
9,E41000299,90,270,373,367,6457,3704,48412,483,193,...,5387,6806,3109,197,5491,17385,15887,17006,173926,17238
10,E41000300,53,1268,37,6238,78,4956,164,34302,330,...,1868,114,2154,197,1161,19381,15343,20284,165800,11031
11,E41000301,344,6641,74,1140,91,6241,127,664,37198,...,1859,57,2758,2193,401,13690,12531,15106,138390,11629
12,E41000302,328,317,5816,434,3329,3835,631,310,283,...,5689,210,6884,437,904,17009,9731,13612,118330,6886
13,E41000303,273,1022,91,706,130,9760,129,592,1205,...,3351,76,7259,1653,732,21861,12060,12556,119051,3803
14,E41000304,20,401,42,1162,68,4674,150,2665,156,...,1938,103,2734,115,2076,26202,10603,8112,100148,4132
15,E41000305,218,3439,62,1138,72,11983,142,776,4954,...,2582,72,3287,1404,594,21687,12640,16423,124845,5218
16,E41000306,62,5040,18,10364,51,4146,129,5024,433,...,1272,44,2182,162,355,11817,11868,12440,114755,12438
17,E41000307,7110,219,415,151,156,2112,99,180,515,...,1601,49,5416,1109,175,12294,8834,12695,113551,14732
18,E41000308,37,784,25,3052,95,2228,107,9560,207,...,879,60,1123,111,348,7790,11415,12223,130973,17442
19,E41000309,29,340,42,1155,81,2398,199,6732,135,...,1191,165,1356,94,1110,10294,11331,13131,127613,14480
20,E41000310,78,1235,51,621,103,13297,149,548,887,...,3090,62,4741,482,639,27343,10254,8768,107255,3914
21,E41000311,16,269,16,664,50,3281,127,778,120,...,1280,50,3955,98,969,27520,13968,5750,82386,3301
22,E41000312,23,121,44,202,99,1872,517,490,56,...,1318,1340,1444,32,2661,8867,9094,6934,82434,11915
23,E41000313,83,540,227,612,1007,9995,2867,775,297,...,10682,856,5540,282,8639,41618,14039,16485,167205,6450
24,E41000314,156,411,1293,475,6437,6021,2164,495,287,...,11735,512,6228,345,1958,22769,11509,14320,136570,5302
25,E41000315,37,235,58,321,319,3530,2775,579,117,...,2749,3929,2516,108,8798,16210,9609,11159,105369,7458
26,E41000316,2851,659,319,913,343,5132,269,709,1066,...,3110,125,11592,3243,864,18262,8994,21268,132787,6864
27,E41000317,4611,627,116,492,186,4238,153,421,1426,...,2315,63,8766,5236,361,16760,11183,14113,125362,9661
28,E41000318,17,167,28,438,60,2978,194,1503,115,...,1776,271,2121,34,2128,14773,14156,7634,99916,10389
29,E41000319,188,488,440,640,1104,8027,1170,561,268,...,25310,347,7802,391,2997,34059,12408,14351,147995,5545
30,E41000320,16,105,94,158,589,1589,5850,279,59,...,1608,23989,1216,51,3785,7927,8882,10050,98207,13794
31,E41000321,561,445,215,386,360,6315,219,467,367,...,4057,118,30488,943,700,29376,9111,10282,121244,4903
32,E41000322,976,1001,100,723,144,6137,183,564,3422,...,2320,81,5282,21581,587,16787,9270,18384,121461,6929
33,E41000323,36,431,81,738,348,8626,1480,1241,260,...,6000,1115,6632,187,23925,46072,16863,13949,179439,9253
34,E41000324,33,712,36,1506,108,7593,164,1080,190,...,2407,63,5897,187,935,49438,16762,7972,117303,5389
46,TOTAL_WORKERS,43647,89244,54602,81732,81922,250615,88324,97801,78599,...,157768,53852,216232,52000,87897,917068,3138022,2513680,30008634,19673047
47,X00000000,10042,17220,15370,11363,13867,51664,13837,14621,17518,...,31899,11845,50811,8261,10466,241192,2750521,2092486,25986853,19387162

In [16]:
#labelling dataframe
jobres.columns = jobres.loc[0]
jobres.drop(0, axis=0, inplace=True)
jobres.set_index('Code', inplace = True)
jobres.head()

,E41000293,E41000294,E41000295,E41000296,E41000297,E41000298,E41000299,E41000300,E41000301,E41000302,...,E41000319,E41000320,E41000321,E41000322,E41000323,E41000324,OD0000001,OD0000003,TOTAL_RESIDENTS,X00000000
Code,,,,,,,,,,,,,,,,,,,,,
E41000293,14650,280,155,290,104,1855,110,250,653,412,...,1218,89,4279,1292,235,6350,4764,10296,75493,6167
E41000294,144,36031,42,5908,91,14006,131,1787,4457,250,...,2357,68,3461,585,567,24662,21611,19791,172470,13371
E41000295,323,131,25876,161,4846,2391,510,177,175,10807,...,4177,136,3656,241,599,12986,8663,11979,110680,12752
E41000296,56,6268,37,27338,84,8735,189,8195,678,221,...,2061,101,2405,276,846,22519,13058,21202,148292,7804
E41000297,135,209,2962,199,41000,4145,4879,275,157,3023,...,6175,887,4946,219,1297,22449,16167,14197,152363,11395

## Creating new category: % working residents that work where they live
- extract relevant data on workers that work where they live
- calculate the value by dividing that + domestic workers by working residents

In [17]:
df = jobres.drop('OD0000001', axis=1)
df.drop('OD0000003', axis=1, inplace=True)
df.drop('X00000000', axis=1, inplace=True)
df.drop('TOTAL_RESIDENTS', axis=1, inplace=True)
df.drop('TOTAL_WORKERS', axis=0, inplace=True)
df.drop('X00000000', axis=0, inplace=True)
df

,E41000293,E41000294,E41000295,E41000296,E41000297,E41000298,E41000299,E41000300,E41000301,E41000302,...,E41000315,E41000316,E41000317,E41000318,E41000319,E41000320,E41000321,E41000322,E41000323,E41000324
Code,,,,,,,,,,,,,,,,,,,,,
E41000293,14650,280,155,290,104,1855,110,250,653,412,...,85,4829,5389,41,1218,89,4279,1292,235,6350
E41000294,144,36031,42,5908,91,14006,131,1787,4457,250,...,208,601,338,383,2357,68,3461,585,567,24662
E41000295,323,131,25876,161,4846,2391,510,177,175,10807,...,191,846,142,91,4177,136,3656,241,599,12986
E41000296,56,6268,37,27338,84,8735,189,8195,678,221,...,284,435,145,522,2061,101,2405,276,846,22519
E41000297,135,209,2962,199,41000,4145,4879,275,157,3023,...,667,518,64,230,6175,887,4946,219,1297,22449
E41000298,51,1918,47,1677,65,23151,98,718,415,216,...,165,370,81,303,2507,49,4192,254,594,29719
E41000299,90,270,373,367,6457,3704,48412,483,193,714,...,4123,433,113,635,5387,6806,3109,197,5491,17385
E41000300,53,1268,37,6238,78,4956,164,34302,330,200,...,437,374,93,1970,1868,114,2154,197,1161,19381
E41000301,344,6641,74,1140,91,6241,127,664,37198,260,...,133,1006,693,134,1859,57,2758,2193,401,13690
E41000302,328,317,5816,434,3329,3835,631,310,283,23759,...,320,1656,223,170,5689,210,6884,437,904,17009
E41000303,273,1022,91,706,130,9760,129,592,1205,449,...,169,1680,489,196,3351,76,7259,1653,732,21861
E41000304,20,401,42,1162,68,4674,150,2665,156,133,...,507,248,38,1147,1938,103,2734,115,2076,26202
E41000305,218,3439,62,1138,72,11983,142,776,4954,317,...,185,841,424,234,2582,72,3287,1404,594,21687
E41000306,62,5040,18,10364,51,4146,129,5024,433,130,...,124,237,91,355,1272,44,2182,162,355,11817
E41000307,7110,219,415,151,156,2112,99,180,515,390,...,66,3567,4882,55,1601,49,5416,1109,175,12294
E41000308,37,784,25,3052,95,2228,107,9560,207,109,...,189,168,73,706,879,60,1123,111,348,7790
E41000309,29,340,42,1155,81,2398,199,6732,135,101,...,342,220,53,7752,1191,165,1356,94,1110,10294
E41000310,78,1235,51,621,103,13297,149,548,887,210,...,143,588,186,187,3090,62,4741,482,639,27343
E41000311,16,269,16,664,50,3281,127,778,120,87,...,222,120,34,338,1280,50,3955,98,969,27520
E41000312,23,121,44,202,99,1872,517,490,56,85,...,3088,94,39,3755,1318,1340,1444,32,2661,8867
E41000313,83,540,227,612,1007,9995,2867,775,297,702,...,2287,597,93,953,10682,856,5540,282,8639,41618
E41000314,156,411,1293,475,6437,6021,2164,495,287,5360,...,651,1163,186,279,11735,512,6228,345,1958,22769
E41000315,37,235,58,321,319,3530,2775,579,117,208,...,16588,256,48,1264,2749,3929,2516,108,8798,16210
E41000316,2851,659,319,913,343,5132,269,709,1066,1311,...,300,24781,3365,214,3110,125,11592,3243,864,18262
E41000317,4611,627,116,492,186,4238,153,421,1426,571,...,111,7676,22053,87,2315,63,8766,5236,361,16760
E41000318,17,167,28,438,60,2978,194,1503,115,104,...,846,104,19,18671,1776,271,2121,34,2128,14773
E41000319,188,488,440,640,1104,8027,1170,561,268,1723,...,782,894,210,456,25310,347,7802,391,2997,34059
E41000320,16,105,94,158,589,1589,5850,279,59,163,...,7117,120,30,812,1608,23989,1216,51,3785,7927
E41000321,561,445,215,386,360,6315,219,467,367,739,...,197,2973,638,248,4057,118,30488,943,700,29376
E41000322,976,1001,100,723,144,6137,183,564,3422,535,...,226,4191,3801,145,2320,81,5282,21581,587,16787
E41000323,36,431,81,738,348,8626,1480,1241,260,353,...,4768,460,71,2674,6000,1115,6632,187,23925,46072
E41000324,33,712,36,1506,108,7593,164,1080,190,144,...,279,320,88,321,2407,63,5897,187,935,49438

In [18]:
jobres.reset_index(inplace=True)
jobres.head()

,Code,E41000293,E41000294,E41000295,E41000296,E41000297,E41000298,E41000299,E41000300,E41000301,...,E41000319,E41000320,E41000321,E41000322,E41000323,E41000324,OD0000001,OD0000003,TOTAL_RESIDENTS,X00000000
0,E41000293,14650,280,155,290,104,1855,110,250,653,...,1218,89,4279,1292,235,6350,4764,10296,75493,6167
1,E41000294,144,36031,42,5908,91,14006,131,1787,4457,...,2357,68,3461,585,567,24662,21611,19791,172470,13371
2,E41000295,323,131,25876,161,4846,2391,510,177,175,...,4177,136,3656,241,599,12986,8663,11979,110680,12752
3,E41000296,56,6268,37,27338,84,8735,189,8195,678,...,2061,101,2405,276,846,22519,13058,21202,148292,7804
4,E41000297,135,209,2962,199,41000,4145,4879,275,157,...,6175,887,4946,219,1297,22449,16167,14197,152363,11395

In [19]:
li = []

In [20]:
for x in df:
    li.append(df[x].loc[x])

In [21]:
lst = pd.DataFrame(li) 
lst

        0
0   14650
1   36031
2   25876
3   27338
4   41000
5   23151
6   48412
7   34302
8   37198
9   23759
10  18889
11  16192
12  15155
13  21485
14  31928
15  45948
16  31030
17  16858
18  10964
19  20982
20  20718
21  20625
22  16588
23  24781
24  22053
25  18671
26  25310
27  23989
28  30488
29  21581
30  23925
31  49438

In [22]:
jobres.reset_index(drop=True, inplace=True)

In [23]:
jobres = pd.concat([jobres, lst], axis=1)

In [24]:
jobres['Residential_Workers_Rate'] = (jobres[0]+jobres["OD0000001"])/jobres["TOTAL_RESIDENTS"]
jobres.head()

,Code,E41000293,E41000294,E41000295,E41000296,E41000297,E41000298,E41000299,E41000300,E41000301,...,E41000321,E41000322,E41000323,E41000324,OD0000001,OD0000003,TOTAL_RESIDENTS,X00000000,0,Residential_Workers_Rate
0,E41000293,14650,280,155,290,104,1855,110,250,653,...,4279,1292,235,6350,4764,10296,75493,6167,14650.0,0.257163
1,E41000294,144,36031,42,5908,91,14006,131,1787,4457,...,3461,585,567,24662,21611,19791,172470,13371,36031.0,0.334215
2,E41000295,323,131,25876,161,4846,2391,510,177,175,...,3656,241,599,12986,8663,11979,110680,12752,25876.0,0.312062
3,E41000296,56,6268,37,27338,84,8735,189,8195,678,...,2405,276,846,22519,13058,21202,148292,7804,27338.0,0.272408
4,E41000297,135,209,2962,199,41000,4145,4879,275,157,...,4946,219,1297,22449,16167,14197,152363,11395,41000.0,0.375203

In [27]:
key.columns = ['code','Borough']
jobres = jobres.merge(key, left_on='Code', right_on ='code')
jobres.drop('code', axis=1, inplace=True)
jobres.head()

,Code,E41000293,E41000294,E41000295,E41000296,E41000297,E41000298,E41000299,E41000300,E41000301,...,E41000322,E41000323,E41000324,OD0000001,OD0000003,TOTAL_RESIDENTS,X00000000,0,Residential_Workers_Rate,Borough
0,E41000293,14650,280,155,290,104,1855,110,250,653,...,1292,235,6350,4764,10296,75493,6167,14650.0,0.257163,Barking and Dagenham
1,E41000294,144,36031,42,5908,91,14006,131,1787,4457,...,585,567,24662,21611,19791,172470,13371,36031.0,0.334215,Barnet
2,E41000295,323,131,25876,161,4846,2391,510,177,175,...,241,599,12986,8663,11979,110680,12752,25876.0,0.312062,Bexley
3,E41000296,56,6268,37,27338,84,8735,189,8195,678,...,276,846,22519,13058,21202,148292,7804,27338.0,0.272408,Brent
4,E41000297,135,209,2962,199,41000,4145,4879,275,157,...,219,1297,22449,16167,14197,152363,11395,41000.0,0.375203,Bromley

In [28]:
PROC_DATA_PATH = '~/library/data/processed/'
jobres.to_csv(PROC_DATA_PATH + 'residents-working-data.csv')